# Generated by Django 5.2.8 on 2025-11-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_inquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'Inquries'},
        ),
    ]
