# Generated by Django 5.2.8 on 2025-11-16 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0003_remove_roofingsheetattribute_gauge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gauge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productgauge'),
        ),
        migrations.AddField(
            model_name='cart',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
