# Generated by Django 5.2.8 on 2025-11-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_gauge_cart_height_cart_length_cart_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price_at_addition',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
