# Generated by Django 5.2.8 on 2025-11-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_price_at_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='profile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
