# Generated by Django 5.2.8 on 2025-11-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_color_order_gauge_order_height_order_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_at_addition',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
