# Generated by Django 5.2.8 on 2025-11-09 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('product_image', models.ImageField(upload_to='products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='RoofingSheetAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], max_length=50)),
                ('gauge', models.CharField(choices=[('26', '26'), ('28', '28'), ('30', '30')], max_length=2)),
                ('profile', models.CharField(choices=[('corrugated', 'Corrugated'), ('ribbed', 'Ribbed')], max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roofing_attributes', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='TileAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Red'), ('brown', 'Brown'), ('gray', 'Gray')], max_length=50)),
                ('gauge', models.CharField(choices=[('26', '26')], max_length=2)),
                ('profile', models.CharField(choices=[('classic', 'Classic'), ('Shingle', 'Shingle'), ('shake', 'Shake'), ('milano', 'Milano')], max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tile_attributes', to='products.product')),
            ],
        ),
    ]
