# Generated by Django 5.2.8 on 2025-11-16 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roofingsheetattribute',
            name='gauge',
        ),
        migrations.RemoveField(
            model_name='tileattribute',
            name='gauge',
        ),
        migrations.CreateModel(
            name='MobileSteelAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(help_text='Price per cubic meter')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='steel_attributes', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gauge', models.CharField(max_length=2)),
                ('price_per_meter', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gauges', to='products.product')),
            ],
        ),
    ]
